"""Eventos internos da fábrica (seção 25 da proposta)."""
from shared.utils.compat import StrEnum


class FactoryEvent(StrEnum):
    PROJECT_CREATED = "project.created"
    DEMAND_CREATED = "demand.created"
    WORKFLOW_STARTED = "workflow.started"
    WORKFLOW_PAUSED = "workflow.paused"
    WORKFLOW_COMPLETED = "workflow.completed"
    WORKFLOW_FAILED = "workflow.failed"
    TASK_CREATED = "task.created"
    TASK_QUEUED = "task.queued"
    TASK_STARTED = "task.started"
    TASK_COMPLETED = "task.completed"
    TASK_FAILED = "task.failed"
    TASK_BLOCKED = "task.blocked"
    AGENT_EXECUTION_STARTED = "agent.execution.started"
    AGENT_EXECUTION_COMPLETED = "agent.execution.completed"
    AGENT_EXECUTION_FAILED = "agent.execution.failed"
    TOOL_EXECUTION_STARTED = "tool.execution.started"
    TOOL_EXECUTION_COMPLETED = "tool.execution.completed"
    TOOL_EXECUTION_FAILED = "tool.execution.failed"
    ARTIFACT_CREATED = "artifact.created"
    ARTIFACT_VERSIONED = "artifact.versioned"
    FINDING_CREATED = "finding.created"
    FINDING_RESOLVED = "finding.resolved"
    APPROVAL_REQUESTED = "approval.requested"
    APPROVAL_APPROVED = "approval.approved"
    APPROVAL_REJECTED = "approval.rejected"
    RISK_CREATED = "risk.created"
    RISK_UPDATED = "risk.updated"
